version: "3"

services:

  ocis:
    image: owncloud/ocis:4
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - web
      - tika
      - appprovider
    entrypoint: "/custom-entrypoint.sh"
    secrets:
      - ocis_jwt-secret
      - ocis_transfer-secret
      - ocis_machine-auth-api-key
      - ocis_storage-system-user-id
      - ocis_storage-system-api-key
      - ocis_idm-admin-password
    volumes:
      - ./config/ocis/scripts/inject-secrets.sh:/custom-entrypoint.sh
      - ./config/ocis/configs:/etc/ocis
      - ocis-data:/var/lib/ocis
    environment:
      - PROXY_TLS=false
      - OCIS_CONFIG_DIR=/etc/ocis/
      - OCIS_DOMAIN=${DOMAINS_OCIS}.${DOMAINS_BASE}
      - SEARCH_EXTRACTOR_TYPE=tika
      - SEARCH_EXTRACTOR_TIKA_TIKA_URL=http://tika
      - FRONTEND_FULL_TEXT_SEARCH_ENABLED=true
      - IDM_CREATE_DEMO_USERS=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.ocis-web.loadbalancer.server.url=http://ocis:9200"
      # HTTP
      - "traefik.http.routers.ocis-web.rule=Host(`${DOMAINS_OCIS}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.ocis-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.ocis-secured.rule=Host(`${DOMAINS_OCIS}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_OCIS}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.ocis-secured.entrypoints=web-secured"
      - "traefik.http.routers.ocis-secured.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Produktivität
      - homepage.name=Cloud
      - homepage.icon=/icons/ocis.svg
      - homepage.href=https://${DOMAINS_OCIS}.${DOMAINS_BASE}
      - homepage.description=Online-Speicher

  # Used for extracting file contents for search
  tika:
    image: apache/tika
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - tika

networks:
  web:
    external: true
  tika:
  appprovider:

volumes:
  ocis-config:
  ocis-data:

secrets:
  ocis_jwt-secret:
    file: ../secrets/ocis_jwt-secret
  ocis_transfer-secret:
    file: ../secrets/ocis_transfer-secret
  ocis_machine-auth-api-key:
    file: ../secrets/ocis_machine-auth-api-key
  ocis_storage-system-user-id:
    file: ../secrets/ocis_storage-system-user-id
  ocis_storage-system-api-key:
    file: ../secrets/ocis_storage-system-api-key
  ocis_idm-admin-password:
    file: ../secrets/ocis_idm-admin-password