base: {{ HOMEPAGE_VAR_BASE_URL }}
title: Dashboard
language: de
target: _blank
headerStyle: clean
layout:
  Produktivität:
    tab: Services
    style: row
    columns: 4
  Sonstige:
    tab: Services
    style: row
    columns: 4
  Server-Management:
    tab: Server-Management
    header: false