base: {{ HOMEPAGE_VAR_BASE_URL }}
title: Dashboard
language: de
target: _blank
headerStyle: clean
layout:
  Produktivität:
    tab: Services
    style: row
  Sonstige:
    tab: Services
    style: row
  Server-Management:
    tab: Server-Management
    header: false