version: "3"

services:

  vaultwarden:
    depends_on:
      - db
    image: vaultwarden/server:latest
    volumes:
      - vaultwarden:/data/
    restart: always
    networks:
      - web
      - db
    logging:
      options:
        max-size: 50m
    environment:
      SIGNUPS_ALLOWED: false
      DOMAIN: https://${VAULTWARDEN_DOMAIN}.${}
      DATABASE_URL: 'postgresql://vaultwarden:${DB_PASSWORD}@db/vaultwarden'
      SMTP_HOST: 
    env_file:
      - .env.vaultwarden
    secrets:
      - domains_base
      - mail_smtp_host
      - mail_smtp_from
      - mail_smtp_port
      - mail_smtp_ssl
      - mail_smtp_username
      - mail_smtp_password
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.vaultwarden-web.loadbalancer.server.url=http://vaultwarden:80"
      # HTTP
      - "traefik.http.routers.vaultwarden-web.rule=Host(`${VAULTWARDEN_DOMAIN}`) || Host(`www.${VAULTWARDEN_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.vaultwarden-secured.rule=Host(`${VAULTWARDEN_DOMAIN}`) || Host(`www.${VAULTWARDEN_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden-secured.entrypoints=web-secured"
      - "traefik.http.routers.vaultwarden-secured.tls.certresolver=tlschallenge"
      # Auth
      #- "traefik.http.routers.vaultwarden-secured.middlewares=traefik-forward-auth@docker"

  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 20m
    environment:
      POSTGRES_USER: vaultwarden
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: vaultwarden

volumes:
  vaultwarden:
  db:

networks:
  web:
    external: true
  db:

secrets:
  domains_base:
    external: true