version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    restart: always
    networks:
      - web
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config.ini:/etc/grafana/grafana.ini
    logging:
      options:
        max-size: 50m
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,marcusolsson-json-datasource
      GF_SERVER_ROOT_URL: https://${GRAFANA_DOMAIN}
    env_file:
      - .env.grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.grafana-web.loadbalancer.server.url=http://grafana:3000"
      # HTTP
      - "traefik.http.routers.grafana-web.rule=Host(`${GRAFANA_DOMAIN}`) || Host(`www.${GRAFANA_DOMAIN}`)"
      - "traefik.http.routers.grafana-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.grafana-secured.rule=Host(`${GRAFANA_DOMAIN}`) || Host(`www.${GRAFANA_DOMAIN}`)"
      - "traefik.http.routers.grafana-secured.entrypoints=web-secured"
      - "traefik.http.routers.grafana-secured.tls.certresolver=tlschallenge"

networks:
  web:
    external: true

volumes:
  grafana-data: