version: "3"

services:
  nextcloud:
    image: nextcloud
    restart: always
    networks:
      - web
      - db
    logging:
      options:
        max-size: 50m
    volumes:
      - nextcloud:/var/www/html
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_DOMAIN},www.${NEXTCLOUD_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.nextcloud-web.loadbalancer.server.url=http://nextcloud:80"
      # HTTP
      - "traefik.http.routers.nextcloud-web.rule=Host(`${NEXTCLOUD_DOMAIN}`) || Host(`www.${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-web.entrypoints=web"
      # Redirect to HTTPS
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.nextcloud-web.middlewares=https_redirect"
      # HTTPS
      - "traefik.http.routers.nextcloud-secured.rule=Host(`${NEXTCLOUD_DOMAIN}`) || Host(`www.${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secured.entrypoints=web-secured"
      - "traefik.http.routers.nextcloud-secured.tls.certresolver=tlschallenge"
      # Allow pinging by dashboard
      - "traefik.http.middlewares.frontend.headers.customresponseheaders.Access-Control-Allow-Origin=${MAIN_DOMAIN}"
  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      options:
        max-size: 20m
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextcloud
  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    networks:
      - web
    env_file:
      - .env.onlyoffice
    environment:
      JWT_ENABLED: true
      JWT_HEADER: Authorization
    logging:
      options:
        max-size: 20m
    volumes:
      - /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
      - onlyoffice-data:/var/www/onlyoffice/Data
      - /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice
      - /app/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq
      - /app/onlyoffice/DocumentServer/redis:/var/lib/redis
      - /app/onlyoffice/DocumentServer/db:/var/lib/postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.onlyoffice-web.loadbalancer.server.url=http://onlyoffice:80"
      # HTTP
      - "traefik.http.routers.onlyoffice-web.rule=Host(`${ONLYOFFICE_DOMAIN}`) || Host(`www.${ONLYOFFICE_DOMAIN}`)"
      - "traefik.http.routers.onlyoffice-web.entrypoints=web"
      # Redirect to HTTPS
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.onlyoffice-web.middlewares=https_redirect"
      # HTTPS
      - "traefik.http.routers.onlyoffice-secured.rule=Host(`${ONLYOFFICE_DOMAIN}`) || Host(`www.${ONLYOFFICE_DOMAIN}`)"
      - "traefik.http.routers.onlyoffice-secured.entrypoints=web-secured"
      - "traefik.http.routers.onlyoffice-secured.tls.certresolver=tlschallenge"

volumes:
  nextcloud:
  pgdata:
  onlyoffice-data:

networks:
  web:
    external: true
  db:
