version: "3"

services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    networks:
      - web
    logging:
      options:
        max-size: 50m
    environment:
      PUID: 1000
      GUID: 1000
      HOMEPAGE_VAR_BASE_URL: https://${DOMAINS_BASE}
    volumes:
      - ./config/homepage/config/bookmarks.yml:/app/config/bookmarks.yaml
      - ./config/homepage/config/docker.yml:/app/config/docker.yaml
      - ./config/homepage/config/services.yml:/app/config/services.yaml
      - ./config/homepage/config/settings.yml:/app/config/settings.yaml
      - ./config/homepage/public:/app/public
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.homepage-web.loadbalancer.server.url=http://homepage:3000"
      # HTTP
      - "traefik.http.routers.homepage-web.rule=Host(`${DOMAINS_BASE}`) || Host(`www.${DOMAINS_BASE}`)"
      - "traefik.http.routers.homepage-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.homepage-secured.rule=Host(`${DOMAINS_BASE}`) || Host(`www.${DOMAINS_BASE}`)"
      - "traefik.http.routers.homepage-secured.entrypoints=web-secured"
      - "traefik.http.routers.homepage-secured.tls.certresolver=tlschallenge"

networks:
  web:
    external: true