version: '3'

services:

  grocy:
    image: linuxserver/grocy
    restart: always
    read_only: true
    volumes:
      - ./grocy-data:/config
    networks:
      - web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      GROCY_CULTURE: de
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.grocy-web.loadbalancer.server.url=http://grocy:80"
      # HTTP
      - "traefik.http.routers.grocy-web.rule=Host(`${GROCY_DOMAIN}`) || Host(`www.${GROCY_DOMAIN}`)"
      - "traefik.http.routers.grocy-web.entrypoints=web"
      # Redirect to HTTPS
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.grocy-web.middlewares=https_redirect"
      # HTTPS
      - "traefik.http.routers.grocy-secured.rule=Host(`${GROCY_DOMAIN}`) || Host(`www.${GROCY_DOMAIN}`)"
      - "traefik.http.routers.grocy-secured.entrypoints=web-secured"
      - "traefik.http.routers.grocy-secured.tls.certresolver=tlschallenge"

networks:
  web:
    external: true

volumes:
  grocy-data: