version: "3"

services:

  resolve-db:
    image: postgres:16-alpine
    restart: always
    networks:
      - web
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 20m
    secrets:
      - resolve-db_username
      - resolve-db_password
    env_file:
      - .env
      - ../.env
    environment:
      POSTGRES_DB: resolve-db
      POSTGRES_USER_FILE: /run/secrets/resolve-db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/resolve-db_password

secrets:
  resolve-db_username:
    file: ../secrets/resolve-db_username
  resolve-db_password:
    file: ../secrets/resolve-db_password

volumes:
  vaultwarden:
  db:

networks:
  web:
    external: true