version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - db
      - web
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.24-amd64
    command: admin start-from-init --masterkey "${ZITADEL_MASTERKEY}"
    environment:
      - ZITADEL_DATABASE_HOST=db
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALDOMAIN=${ZITADEL_DOMAIN}
    healthcheck:
      test: ["CMD", "zitadel", "admin", "status", "health"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.zitadel-web.loadbalancer.server.url=http://zitadel:8080"
      # HTTP
      - "traefik.http.routers.zitadel-web.rule=Host(`${ZITADEL_DOMAIN}`) || Host(`www.${ZITADEL_DOMAIN}`)"
      - "traefik.http.routers.zitadel-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.zitadel-secured.rule=Host(`${ZITADEL_DOMAIN}`) || Host(`www.${ZITADEL_DOMAIN}`)"
      - "traefik.http.routers.zitadel-secured.entrypoints=web-secured"
      - "traefik.http.routers.zitadel-secured.tls.certresolver=tlschallenge"

  db:
    restart: always
    networks:
      - db
    image: cockroachdb/cockroach:v22.1.0
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    volumes:
      - cockroachdata:/cockroach/cockroach-data
#     ports:
#       - 9090:8080
#       - 26257:26257

volumes:
  cockroachdata:

networks:
  db:
  web:
    external: true