version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - db
      - web
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.15-amd64
    command: admin start-from-init --masterkeyFromEnv
    environment:
      - ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}
      - ZITADEL_DATABASE_HOST=db
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=${ZITADEL_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/debug"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.zitadel-web.loadbalancer.server.url=http://zitadel:8080"
      # HTTP
      - "traefik.http.routers.zitadel-web.rule=Host(`${ZITADEL_DOMAIN}`) || Host(`www.${ZITADEL_DOMAIN}`)"
      - "traefik.http.routers.zitadel-web.entrypoints=web"
      # Redirect to HTTPS
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.zitadel-web.middlewares=https_redirect"
      # HTTPS
      - "traefik.http.routers.zitadel-secured.rule=Host(`${ZITADEL_DOMAIN}`) || Host(`www.${ZITADEL_DOMAIN}`)"
      - "traefik.http.routers.zitadel-secured.entrypoints=web-secured"
      - "traefik.http.routers.zitadel-secured.tls.certresolver=tlschallenge"

  db:
    restart: always
    networks:
      - db
    image: cockroachdb/cockroach:v21.2.5
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    volumes:
      - cockroachdata:/cockroach/cockroach-data
#     ports:
#       - 9090:8080
#       - 26257:26257

volumes:
  cockroachdata:

networks:
  db:
  web:
    external: true